---
- name: Ensure install directory existence
  ansible.builtin.file:
    path: "{{ mcj_install_dir }}"
    state: directory
    mode: "0755"

- name: Ensure sub directories existence
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ mcj_install_dir }}/bin"
    - "{{ mcj_install_dir }}/workspace"

- name: "Get the status of Minecraft Server {{ mcj_minecraft_version }} jar file"
  ansible.builtin.stat:
    path: "{{ mcj_install_dir }}/bin/minecraft_server.{{ mcj_minecraft_version }}.jar"
  register: minecraft_server_version_jar_file

- name: Download Minecraft Server jar file
  ansible.builtin.get_url:
    url: "{{ minecraft_versions[mcj_minecraft_version]['url'] }}"
    dest: "{{ mcj_install_dir }}/bin/server.jar"
    mode: "0644"
  when: not minecraft_server_version_jar_file.stat.exists

- name: Get the status of downloaded Minecraft Server jar file
  ansible.builtin.stat:
    path: "{{ mcj_install_dir }}/bin/server.jar"
    checksum_algorithm: sha1
  register: minecraft_server_jar_file
  when: not minecraft_server_version_jar_file.stat.exists

- name: Fail if downloaded Minecraft Server jar file checksum does not match
  ansible.builtin.fail:
    msg: "Downloaded Minecraft Server jar file checksum {{ minecraft_server_jar_file.stat.checksum }} does not match the expected checksum {{ minecraft_versions[mcj_minecraft_version]['sha1'] }}"
  when: not minecraft_server_version_jar_file.stat.exists and minecraft_server_jar_file.stat.checksum != minecraft_versions[mcj_minecraft_version]['sha1']

- name: "Copy downloaded Minecraft Server jar file as Minecraft Server {{ mcj_minecraft_version }} jar file"
  ansible.builtin.copy:
    remote_src: true
    src: "{{ mcj_install_dir }}/bin/server.jar"
    dest: "{{ mcj_install_dir }}/bin/minecraft_server.{{ mcj_minecraft_version }}.jar"
    mode: "0644"
  when: not minecraft_server_version_jar_file.stat.exists and minecraft_server_jar_file.stat.exists

- name: Delete downloaded Minecraft Server jar file
  ansible.builtin.file:
    path: "{{ mcj_install_dir }}/bin/server.jar"
    state: absent

- name: "Get the status of Minecraft Server jar file"
  ansible.builtin.stat:
    path: "{{ mcj_install_dir }}/bin/minecraft_server.jar"
  register: minecraft_server_jar_file

- name: "Ensure Minecraft Server jar file or symlink does not exist"
  ansible.builtin.file:
    path: "{{ mcj_install_dir }}/bin/minecraft_server.jar"
    state: absent
  when: not minecraft_server_jar_file.stat.exists

- name: Create symbolic link for Minecraft Server jar file
  ansible.builtin.file:
    src: "{{ mcj_install_dir }}/bin/minecraft_server.{{ mcj_minecraft_version }}.jar"
    dest: "{{ mcj_install_dir }}/bin/minecraft_server.jar"
    state: link

# Minecraft server would add any missing properties with default values
# hence it's not necessary to specify all properties in mcj_server_properties.
- name: "Set Minecraft server configuration values"
  ansible.builtin.lineinfile:
    path: "{{ mcj_install_dir }}/workspace/server.properties"
    regexp: '^{{ item.key }}='
    line: '{{ item.key }}={{ item.value }}'
    create: yes
    mode: "0644"
  loop: "{{ mcj_server_properties | dict2items }}"

- name: "Get the status of Minecraft Server service file"
  ansible.builtin.stat:
    path: "/etc/systemd/system/{{ mcj_id }}.service"
  register: minecraft_service_file

- name: "Get the status of Minecraft Server start script file"
  ansible.builtin.stat:
    path: "{{ mcj_install_dir }}/bin/start.sh"
  register: minecraft_start_script_file

- name: "Create Minecraft Server start script"
  ansible.builtin.copy:
    content: |
      #!/bin/bash
      java {{ mcj_java_opts }} -jar {{ mcj_install_dir }}/bin/minecraft_server.jar nogui
    dest: "{{ mcj_install_dir }}/bin/start.sh"
    mode: "0755"
  when: not minecraft_start_script_file.stat.exists

- name: "Create Minecraft Server service file"
  become: yes
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=Minecraft Java
      After=network.target

      [Service]
      ExecStart={{ mcj_install_dir }}/bin/start.sh
      Environment=PATH={{ mcj_env_path }}
      WorkingDirectory={{ mcj_install_dir }}
      Restart=on-failure
      RestartSec=10s
      User={{ mcj_user }}

      [Install]
      WantedBy=multi-user.target
    dest: "/etc/systemd/system/{{ mcj_id }}.service"
    mode: "0644"
  when: not minecraft_service_file.stat.exists

- name: "Check init system"
  ansible.builtin.command: ps -p 1 -o comm=
  changed_when: false
  register: init_system_check

- name: "Enable Mincraft Server service with systemd"
  become: yes
  ansible.builtin.systemd:
    name: "{{ mcj_id }}.service"
    enabled: yes
    state: stopped
  when: init_system_check.stdout.strip() == "systemd"

- name: "Create aliases for Minecraft Server generic utilities"
  ansible.builtin.include_role:
    name: ansible-roles.bash_aliases
  vars:
    bash_aliases:
      - alias: "{{ mcj_id }}-conf"
        command: "vi {{ mcj_install_dir }}/workspace/server.properties"
      - alias: "{{ mcj_id }}-log"
        command: "tail -f {{ mcj_install_dir }}/workspace/logs/latest.log"

- name: "Create aliases for Minecraft Server systemd utilities"
  ansible.builtin.include_role:
    name: ansible-roles.bash_aliases
  vars:
    bash_aliases:
      - alias: "{{ mcj_id }}-start"
        command: "cd {{ mcj_install_dir }}/workspace/ && systemctl start {{ mcj_id }}.service"
      - alias: "{{ mcj_id }}-stop"
        command: "systemctl stop {{ mcj_id }}.service"
      - alias: "{{ mcj_id }}-status"
        command: "systemctl status {{ mcj_id }}.service"
      - alias: "{{ mcj_id }}-start-log"
        command: "journalctl -u {{ mcj_id }}"
  when: init_system_check.stdout.strip() == "systemd"
  